apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dr5lb1d4f-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:6dfd1c4011c92d4dfa9b3736dbf25acfdf86b1f2@sha256:974e95b24b0586c9c24cc2a94d8699a0c6032a8e6663c57a37b6b2280416fbef
          name: container-image
