apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dr5lb1d4f-java-springboot
  janus-idp.io/tekton: dr5lb1d4f-java-springboot
  backstage.io/kubernetes-id: dr5lb1d4f-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dr5lb1d4f-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
